### ISSUE TITLE
希望能考慮到一個問題

### ISSUE THREAD

**Issue by 98Kstar** [TheKingOfDuck/burpFakeIP#1]
希望表哥能考慮到一個問題，我在使用該插件隨機ip對用戶名、密碼時進行爆破，發現ip一直在變，但是爆破的用戶名根密碼一直不變。相當於我希望有三個變量同時在變，不知是我未設置正確還是表哥您沒考慮到這個問題。

**Comment by TheKingOfDuck** [comment]
> 希望表哥能考慮到一個問題，我在使用該插件隨機ip對用戶名、密碼時進行爆破，發現ip一直在變，但是爆破的用戶名根密碼一直不變。相當於我希望有三個變量同時在變，不知是我未設置正確還是表哥您沒考慮到這個問題。

我在README.MD里面其实写的，方法如下：

将数据包发送到Intruder模块,在Positions中切换Attack type为Pitchfork模式,选择好有效的伪造字段,以及需要爆破的字段:

将Payload来源设置为Extensin-generated,并设置负载伪fakeIpPayloads,然后设置第二个变量。 

点击Start attack开始爆破.
