### ISSUE TITLE
不知道是软件BUG还是插件bug,当我用户名密码双爆破的时候,会一直是一个用户名密码,无法向下执行

### ISSUE THREAD

**Issue by hktkqwe123** [TheKingOfDuck/burpFakeIP#10]
[不知道是软件BUG还是插件bug,当我用户名密码双爆破的时候,会一直是一个用户名密码,无法向下执行
![360截图20210726233804783](https://user-images.githubusercontent.com/45476209/127017728-c72609b1-ae0d-40b4-994d-dfbbe52287c4.png)

**Comment by TheKingOfDuck** [comment]
> [不知道是软件BUG还是插件bug,当我用户名密码双爆破的时候,会一直是一个用户名密码,无法向下执行
> ![360截图20210726233804783](https://user-images.githubusercontent.com/45476209/127017728-c72609b1-ae0d-40b4-994d-dfbbe52287c4.png)

这个问题我遇到过，是burp的Intruder本身不支持多种Attack Type导致的问题，插件本身只是返回一个随机生成的ip而已，一般用Pitchfork模式就可以了 但要账号密码同时爆破的话需要用Cluster bomb模式。两则不可同时使用。


不过也有解决方法，Attack Type使用Pitchfork模式，ip是一个变量1，将用户名密码设置为变量2  变量2里面的payload type选Custom iterator，再把账号密码相关字段拼接出来就行。

**Comment by hktkqwe123** [comment]
问一下怎么拼接啊？萌新不太会呢！！！！！！
