### ISSUE TITLE
上传文件不完整

### ISSUE THREAD

**Issue by M00nBack** [TheKingOfDuck/burpFakeIP#11]
不知道为啥 开启这个插件我上传的文件内容就不完整了

**Comment by TheKingOfDuck** [comment]
> 不知道为啥 开启这个插件我上传的文件内容就不完整了

啊哈？理论上不应该啊，插件本身没有去修改编码之类的东西  可能是burp的bug 啥版本啊 最好加wx发截图这种解决问题会快很多
