### ISSUE TITLE
Not working on Latest version of BurpSuite v2020.9.2

### ISSUE THREAD

**Issue by teslatheg0d** [TheKingOfDuck/burpFakeIP#4]
![Screenshot from 2020-10-09 21-37-04](https://user-images.githubusercontent.com/61558155/95606185-9a3ce480-0a77-11eb-8062-986e72c2d2c9.png)

The current version of Jython is 2.7.2.

**Comment by Slingx** [comment]
Yes i tried with the jython 2.0 too. Didn't work on latest burp. Same error.

**Comment by TheKingOfDuck** [comment]
![workinmyway](https://user-images.githubusercontent.com/27769271/103120687-cbf73c00-46b3-11eb-8779-eeb28df83ec1.png)

My env: BurpSuite v2020.12.1 + jython 2.7.0

it works.

**Comment by teslatheg0d** [comment]
can you tell us that 

what does that error is saying and means..???
