### ISSUE TITLE
如果每次生成xff头前能先检查下是否已存在，若已存在则替换其内容，反之则新增

### ISSUE THREAD

**Issue by Wnltc** [TheKingOfDuck/burpFakeIP#8]
每次都直接新增xff头的话，在repeater模块会多上一堆重复的xff头，如果能每次新增前能先检查下，如果已经有某个头则替换掉其内容，反之新增头部，就更nice了。

![image](https://user-images.githubusercontent.com/29775532/112929836-cb0af600-914b-11eb-83e5-ce30f1c962c6.png)

**Comment by TheKingOfDuck** [comment]
> 每次都直接新增xff头的话，在repeater模块会多上一堆重复的xff头，如果能每次新增前能先检查下，如果已经有某个头则替换掉其内容，反之新增头部，就更nice了。
> 
> ![image](https://user-images.githubusercontent.com/29775532/112929836-cb0af600-914b-11eb-83e5-ce30f1c962c6.png)

好的，后面有时间就改下这个问题

**Comment by TheKingOfDuck** [comment]
> 每次都直接新增xff头的话，在repeater模块会多上一堆重复的xff头，如果能每次新增前能先检查下，如果已经有某个头则替换掉其内容，反之新增头部，就更nice了。
> 
> ![image](https://user-images.githubusercontent.com/29775532/112929836-cb0af600-914b-11eb-83e5-ce30f1c962c6.png)

这个功能已经加上了
